Feature/#19 feature 회원가입 및 시큐리티 적용
2023Summer/mr-playlist-backend pull request #24
Opened 2023-07-27 06:25 UTC by jw-jin

회원가입 및 이메일 인증 추가,
issue#19

후에 로그인 JWT 작업 하면서 시큐리티도 제대로 설정할 예정

2023-07-27 07:01 UTC, shinb-bong requested changes
고생하셨습니당 😊

2023-07-27 07:01 UTC, shinb-bong commented on src/main/java/summer/mrplaylist/member/dto/AddMemberRequestDto.java
파일명 나중에 한번 컨벤션 일치시키긴해야겠네 ㅋㅋㅋㅋㅋㅋ

2023-07-27 07:38 UTC, jw-jin commented on src/main/resources/application.yml
> +
몰랐던 사실이네요 말씀 감사합니다!

2023-07-27 07:41 UTC, jw-jin commented on src/main/resources/application.yml
> +    username: ${SMTP_EMAIL}
넵 필요하다면 각자의 구글 아이디로 SMTP 설정해놓으면 인텔리제이상 환경 변수 설정이나 기타 환경 변수 설정을 통해 사용 가능할 것 같습니다

2023-07-27 07:43 UTC, jw-jin commented on src/main/java/summer/mrplaylist/member/service/MemberService.java
> +            throw new IllegalStateException("이미 존재하는 이메일");
> 추후에 자주 사용하는 내용이면 별도의 constant 로 빼도 좋을 듯합니당

"이미 존재하는 이메일" 문자열 말씀이신가요?

2023-07-27 07:44 UTC, jw-jin commented on src/main/java/summer/mrplaylist/member/model/Member.java
> 깔끔하게 잘짰네요 굿굿 `@NoArgsConstructor` 만 추후 다른 곳에서 생성하지 못하게 protected 설정 부탁드립니다.

앗 빠진부분이 있었네요!! 좋은 지적 감사합니다!

2023-07-27 07:46 UTC, jw-jin commented on src/main/java/summer/mrplaylist/member/service/MemberService.java
> +        Member member = memberRepository.findById(id).orElseThrow(() -> new IllegalArgumentException("해당 id의 회원 없음"));
> 이 부분도 column 을 보여주는것보단 "해당 회원이 없습니다." 등으로 해야 보안도하고 추후에 에러메세지도 통일할수 있습니다

넵 지적 감사합니다!

2023-07-27 07:52 UTC, jw-jin commented on src/main/java/summer/mrplaylist/member/service/MemberService.java
> +            throw new IllegalStateException("이미 존재하는 이메일");
아직은 괜찮은것 같은데 후에 필요하다 판단되면 추가하겠습니다!

2023-07-27 07:53 UTC, jw-jin commented on src/main/java/summer/mrplaylist/member/service/MemberService.java
> +public class MemberService {
넵 추가했습니다!

2023-07-27 07:56 UTC, jw-jin commented on src/test/java/summer/mrplaylist/member/service/EmailServiceTest.java
지금 이메일 전송 기능만 테스트코드가 작성되어 있는데 인증메일 부분도 추가할 예정입니다!

2023-07-27 07:56 UTC, jw-jin commented on src/test/java/summer/mrplaylist/common/config/db/RedisConfigTest.java
> +class RedisConfigTest {
넵 참고하겠습니당!

2023-07-27 09:38 UTC, jw-jin commented on src/test/java/summer/mrplaylist/member/service/EmailServiceTest.java
에러로 인해 테스트 코드 부분은 삭제하겠습니다..

2023-07-28 01:55 UTC, shinb-bong approved these changes
고생하셨습니당

2023-08-01 02:40 UTC, shinb-bong approved these changes
고생하셨습니당

2023-08-01 04:34 UTC, jw-jin commented on src/main/java/summer/mrplaylist/common/config/jwt/JwtProperties.java
> +public interface JwtProperties {
넵 알겠습니다!

2023-08-01 06:34 UTC, merged