Feat: Playlist 댓글
2023Summer/mr-playlist-backend pull request #41
Opened 2023-08-07 01:09 UTC by ShsH0920

댓글 작성, 수정, 삭제 기능 작성
issue #36

## 개요

댓글 작성, 수정, 삭제 기능을 작성했습니다.
Comment, CommentRepository, CommentService, CommentForm 작성
PlayList에 commentCount, commentList를 추가했습니다. (한 플레이리스트 당 여러 comment) 

## PR 유형
어떤 변경 사항이 있나요?

- [x] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다.  Commit message convention 참고  (Ctrl + 클릭하세요.)
- [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

2023-08-07 06:08 UTC, jw-jin commented on src/main/java/summer/mrplaylist/comment/controller/CommentController.java
> +@Controller
아직 컨트롤러 내용 작성은 안하셨지만 기능 거의 대부분 REST API 형태로 작성되어야 되서 RestController를 사용하는게 맞을것 같습니다!

2023-08-07 06:15 UTC, jw-jin commented on src/main/java/summer/mrplaylist/comment/dto/CommentForm.java
> +    private Member member;
Comment와 CommentForm의 내용이 반대가 된것 같네요! 그리고 Form의 내용은 프론트로부터 전달된 값이니까 Playlist의 아이디와 콘텐츠만 전달되면 될 것 같습니다!

2023-08-07 06:19 UTC, jw-jin commented on src/main/java/summer/mrplaylist/comment/dto/CommentForm.java
> +    private LocalDateTime createdAt;
createAt은 JPA auditing을 통해 Comment 객체 생성시 자동으로 매핑 되므로 따로 안넣어 주셔도 됩니다!

2023-08-07 06:24 UTC, jw-jin commented on src/main/java/summer/mrplaylist/comment/dto/CommentForm.java
> +    private Member member;
멤버 객체를 사용해도 상관 없구요!

2023-08-07 06:31 UTC, jw-jin commented on src/main/java/summer/mrplaylist/comment/model/Comment.java
>  public class Comment {
위에 말씀드렸던대로 여기에 Playlist, member 필드가 들어가면 될 것 같습니다!

2023-08-07 06:43 UTC, jw-jin commented on src/main/java/summer/mrplaylist/comment/service/CommentService.java
기능 동작시에 예외 검사 및 처리를 추가하면 더 좋을것 같습니다!

2023-08-07 06:45 UTC, jw-jin commented on src/main/java/summer/mrplaylist/comment/service/CommentService.java
> +@Transactional(readOnly = true)
@Transactional 만 달아서 아래 어노테이션을 지우고 나중에 Transactional(readOnly = true) 어노테이션을 필요한 부분에다 달아서 사용하는 게 더 깔끔할 것 같아요!

2023-08-07 06:49 UTC, jw-jin requested changes
고생하셨어요! 댓글 남겨드린 부분 확인해주시면 될 것 같습니다!

2023-08-07 06:50 UTC, shinb-bong commented on src/main/java/summer/mrplaylist/comment/service/CommentService.java
> +@Transactional(readOnly = true)
보통은 C U D가 20프로고 R이 80프로라서 이렇게 작성하는 것이 편리하긴 해용.(개인적으로 이 방법 선호)
하지만 지금 설계라면  댓글같은 경우는 단순 출력이라서 이 방법이 편리할수도 있겠네요

2023-08-07 06:59 UTC, shinb-bong commented on src/main/java/summer/mrplaylist/comment/service/CommentService.java
`@Repository` 를 달게되면 컴포넌트 스캔의 대상과 앞서 말씀해주신 말처럼 예외를 스프링 예외로 변환시켜줍니다.

하지만 JpaRepository 의 다이어그램을 보게되면 상위에 `SimpleJpaRepository` 가 존재하는데 해당 코드에 
![image](https://github.com/2023Summer/mr-playlist-backend/assets/81786969/abae972e-77d5-4d19-b723-803afca5edf0)
가 있기에 작성을 생략해도됩니다.

2023-08-07 07:32 UTC, shinb-bong requested changes

2023-08-07 07:32 UTC, shinb-bong commented on src/main/java/summer/mrplaylist/comment/service/CommentService.java
> +        Comment comment = commentRepository.getReferenceById(commentId);
여기 `findById`로 해주세용 
설명은 음 잘 되어있는 블로그 하나 첨부할께요

https://bcp0109.tistory.com/325

2023-08-07 07:36 UTC, shinb-bong requested changes
그래도 수정해서 곧 완성 할 것 같은데 
해당 메소드들이 수행되는지는 단위테스트를 경험하면 가장 좋겠지만
일단 추천해드린 강의에서 나온 것처럼 통합테스트(`@SpringbootTest`) 라도 진행해서 적어도 1개 만들어주세요.

2023-08-07 07:36 UTC, shinb-bong commented on src/main/java/summer/mrplaylist/playlist/model/Playlist.java
> +    @Column(name = "comment_count", nullable = false)
필드값 추가한 사항들 PR 통과해서 Merge 하면 erdcloud에 최신화 해주시고
해당 필드값 자체 객체여서 빌더시에 기본값 없으면 `null` 값이 들어갑니다.
아래 생성 메소드`createPlaylist` 만들 때도 추가해주셔야합니다.

2023-08-09 01:14 UTC, shinb-bong requested changes
조금만 더 수정하면 될듯하고 
더 집어드릴 곳은 오늘 설명 해드릴께요

2023-08-09 01:14 UTC, shinb-bong commented on src/main/java/summer/mrplaylist/comment/service/CommentService.java
> +        comment.get().update(commentForm.getContent());
`.ElseThrow()` 문법 한번 찾아서 적용해보세용

2023-08-09 01:14 UTC, shinb-bong commented on src/main/java/summer/mrplaylist/comment/service/CommentService.java
> +        commentRepository.deleteById(commentId);
해당 만약에 
현재 수현님이 짠것처럼 진행하면 삭제할때도 플레이리스트에서 카운트 숫자를 줄여줘야합니다.

2023-08-09 06:02 UTC, shinb-bong requested changes

2023-08-09 06:02 UTC, shinb-bong commented on src/main/java/summer/mrplaylist/comment/service/CommentService.java
> +        Comment comment = commentRepository.findById(commentId).orElseThrow(() -> new NoSuchElementException());
`IllegalStateException`로 변경부탁드리고
왜 에러가 터지게되는지 에러메세지도 명명 부탁드립니다.

https://velog.io/@injoon2019/IllegalArgumentException-vs-IllegalStateException

2023-08-10 08:22 UTC, ShsH0920 commented on src/main/java/summer/mrplaylist/comment/dto/CommentForm.java
> +    private Member member;
반영했습니다!!!!

2023-08-10 08:22 UTC, ShsH0920 commented on src/main/java/summer/mrplaylist/comment/dto/CommentForm.java
> +    private LocalDateTime createdAt;
createAt 삭제했어요 감사합니당

2023-08-10 08:23 UTC, ShsH0920 commented on src/main/java/summer/mrplaylist/comment/model/Comment.java
>  public class Comment {
comment, commentForm 수정했습니다!!

2023-08-11 02:03 UTC, merged

2023-08-11 02:05 UTC, shinb-bong reviewed
코드 컨벤션 넣기 코드라 확인 완료 후 충돌 해결하여 합쳤습니다.